return {
	-- Highlight, edit, and navigate code
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			ignore_install = {},
			sync_install = false,
			modules = {},
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
				notify_on_error = true,
				disable = {},
			},
			indent = { enable = true },
			fold = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"cmake",
				"cpp",
				"csv",
				"cuda",
				"doxygen",
				"html",
				"latex",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"matlab",
				"python",
				"query",
				"regex",
				"ron",
				"rust",
				"typst",
				"verilog",
				"vhdl",
				"vim",
				"vimdoc",
				"yaml",
			},
		})
	end,
}
