[mgr]

# --- Custom keybindings ---
[[mgr.prepend_keymap]]
on = ["g", "."]
run = "cd ~/.dotfiles"
desc = "Go to dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /media/$USER"
desc = "Go to media"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go back to the root of the current Git repository"

# --- eza-preview plugin ---
[[mgr.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[mgr.prepend_keymap]]
on = ["-"]
run = "plugin eza-preview --args='inc-level'"
desc = "Increment tree level"

[[mgr.prepend_keymap]]
on = ["_"]
run = "plugin eza-preview --args='dec-level'"
desc = "Decrement tree level"

[[mgr.prepend_keymap]]
on = ["$"]
run = "plugin eza-preview --args='toggle-follow-symlinks'"
desc = "Toggle tree follow symlinks"

# --- chmod plugin ---
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# --- lazygit plugin ---
[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "Run lazygit"

# --- toggle-pane plugin ---
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Show or hide the preview pane"
