[flavor]

# cattpuccin theme
dark = "catppuccin-mocha"
# light = "catppuccin-latte"

# everforest theme
# dark = "everforest-medium"

# Moonfly theme
# dark = "moonfly"

# vscode dark
# dark = "vscode-dark-modern"
