# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode     = "size"
show_hidden  = false
sort_by      = "natural"
ratio        = [2, 4, 4]
show_symlink = false

[preview]
tab_size   = 4
max_width  = 1000
max_height = 1000

# ========================
# OPENERS
# ========================
[opener]
# 1. Define the apps/commands
edit = [
  { run = 'nvim "$@"', desc = "nvim", block = true }
]
play = [
  { run = 'mpv --force-window "$@"', desc = "mpv" }
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" }
]

# 2. Define the rules (Yazi looks for these specifically under [opener])

[open]

prepend_rules = [
  { url = "*/", use = ["open", "edit"] },
  { mime = "text/*", use = ["edit", "reveal"] },
  { mime = "image/*", use = ["open", "reveal"] },
  { mime = "video/*", use = ["play", "reveal"] },
  { mime = "audio/*", use = ["play", "reveal"] },
  { mime = "inode/x-empty", use = ["edit", "reveal"] },
]

append_rules = [
  { url = "*", use = ["open", "reveal"] },
]

# ========================
# PLUGINS
# ========================
[plugin]

prepend_previewers = [
  { mime = "audio/*", run = "exifaudio" },
  { url = "*/", run = "eza-preview" },
  { url = "*.csv", run = "rich-preview"},
  { url = "*.md", run = "rich-preview" },
  { url = "*.rst", run = "rich-preview"},
  { url = "*.ipynb", run = "rich-preview"},
  { url = "*.json", run = "rich-preview"},
]

# --- Fetchers ---
[[plugin.prepend_fetchers]]
# id   = "git"
url = "*"
run  = "git"
group = "git"

[[plugin.prepend_fetchers]]
# id   = "git"
url = "*/"
run  = "git"
group = "git"
