fork = false
frame = "full"
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
mouse-cursor-icon = "arrow" # i-beam
title-hidden = true
vsync = true

[font]
normal = ["JetBrainsMono Nerd Font"]
size = 14.0

[box-drawing]
mode = "selected-native"
selected = "   🮑🮒  ▕▏▁▁ ▄▐ ▌█"

