[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = ["fd -H -t f -E .git . $HOME/.dotfiles", "fd -t f . $HOME/.config"]


[preview]
command = "bat -n --color=always {}"

[keybindings]
shortcut = "f5"
