[metadata]
name = "manpages"
description = "A channel to select from manpages"
requirements = ["bat"]

[source]
command = ["man -k ."]
display = "{split: :0..2}"
output = "{split: :0}"

[preview]
command = "man {0} | bat --language=man -p --color=always"

[keybindings]
ctrl-e = "actions:open"
shortcut = "f10"

[actions.open]
description = "Open the selected manpage"
command = "man {0}"
mode = "execute"

[ui.preview_panel]
size = 75
header = "{split:-:1..}"
