[metadata]
name = "Projects"
description = "A channel to select from `Projects` directory"
requirements = ["fd", "eza"]

[source]
command = ["fd -t d -d 1 . ~/Projects/"]
display = "{split:/:4}"

[preview]
command = "eza --long --git --all --color=always --icons=always {}"

[keybindings]
shortcut = "f4"
