# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

# Color pallet for the prompt
palette = "catppuccin_mocha"

# Use custom format
format = """
[╭─](text)$username$hostname in $directory$c$custom$java$lua$python$rust$package$git_branch$battery$cmd_duration
[╰─](text)$character 
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Username settings
[username]
show_always = true
style_root = "red"
style_user = "yellow"
format = "[$user]($style) "
disabled = false

# Hostname settings
[hostname]
ssh_only = false
format =  "on [$hostname](red)"
trim_at = ".companyname.com"
disabled = false

# Directory indicator
[directory]
read_only = "🔒"
style = "bold cyan"
read_only_style = "red"
truncation_length = 8
truncation_symbol = "…/"
format = "[$read_only]($read_only_style)[$path]($style) "
disabled = false

# C language settings
[c]
symbol = " "
style = "blue bold"
format = "via [${symbol}${version}]($style) "

# C++ language settings
[custom.cpp]
detect_extensions = ['cpp', 'hpp']
symbol = " "
style = "blue bold"
format = "via [${symbol}${output}]($style) "
command = "g++ --version | awk 'NR==1 {print $4}'"

# Java settings
[java]
symbol = "☕ "
style = "red dimmed"
format = "via [${symbol}${version}]($style) "

# Lua language settings
[lua]
symbol = "🌙 "
# style = "bright_yellow bold"
style = "peach bold"
format = "via [${symbol}Lua ${version}]($style) "

# Python settings
[python]
symbol = "🐍 "
style = "yellow bold"
format = "via [${symbol}${version}]($style) "
python_binary = "python3"
# pyenv_version_name = true

# Rust language settings
[rust]
symbol = "🦀 "
# style = "bright_red bold"
style = "maroon bold"
format = "via [${symbol}Rust ${version}]($style) "

# Package Version Config
[package]
symbol = "🎁 "
# style = "bright_yellow bold"
style = "peach bold"
format = "in [${symbol}$version]($style) "

# git settings
[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

# Battery information
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "red"

# cmd_duration config
[cmd_duration]
show_milliseconds = true
style = "bold yellow"
format = "took [$duration]($style)"

# Charakter config
[character]

format = "$symbol"
success_symbol = "[](green)"
error_symbol = "[](red) "
vicmd_symbol = "[❮](green)"
disabled = false

[palettes.catppuccin_mocha]
  rosewater     = "#f5e0dc"
  flamingo      = "#f2cdcd"
  pink          = "#f5c2e7"
  mauve         = "#cba6f7"
  red           = "#f38ba8"
  maroon        = "#eba0ac"
  peach         = "#fab387"
  yellow        = "#f9e2af"
  green         = "#a6e3a1"
  teal          = "#94e2d5"
  sky           = "#89dceb"
  sapphire      = "#74c7ec"
  blue          = "#89b4fa"
  lavender      = "#b4befe"
  text          = "#cdd6f4"
  subtext1      = "#bac2de"
  subtext0      = "#a6adc8"
  overlay2      = "#9399b2"
  overlay1      = "#7f849c"
  overlay0      = "#6c7086"
  surface2      = "#585b70"
  surface1      = "#45475a"
  surface0      = "#313244"
  base          = "#1e1e2e"
  mantle        = "#181825"
  crust         = "#11111b"


[palettes.github_dark_tritanopia]
  blue =          "#58a6ff"
  red =           "#ff7b72"
  green =         "#58a6ff"
  yellow =        "#d29922"
  purple =        "#bc8cff"
  cyan =          "#39c5cf"
  white =         "#b1bac4"
  black =         "#484f58"
  bright-black =  "#6e7681"
  bright-red =    "#ffa198"
  bright-green =  "#79c0ff"
  bright-yellow = "#e3b341"
  bright-blue =   "#79c0ff"
  bright-purple = "#d2a8ff"
  bright-cyan =   "#56d4dd"

[palettes.oldworld]
  black         = "#27272a"
  red           = "#ea83a5"
  green         = "#90b99f"
  yellow        = "#e6b99d"
  blue          = "#9ca2cf"
  purple        = "#aca1cf"
  cyan          = "#85b5ba"
  white         = "#c9c7cd"

  bright_black  = "#353539"
  bright_red    = "#ED96B3"
  bright_green  = "#a7c8b3"
  bright_yellow = "#eac5ae"
  bright_blue   = "#acb1d7"
  bright_purple = "#b7aed5"
  bright_cyan   = "#97c0c4"
  bright_white  = "#d3d1d7"

[palettes.moonfly]
  fern          = "#87d787"
  lavender      = "#adadf3"
  orange        = "#f09479"
  red           = "#ff5189"
  blue          = "#80a0ff"
  cyan          = "#79dac8"
  purple        = "#cf87e8"
  yellow        = "#e3c78a"
  green         = "#8cc85f"
  bright_red    = "#f07496"
  bright_yellow = "#c6c684"
