return {
	lsp = {
		arduino_language_server = {},
		-- asm_lsp = {},
		bashls = {},
		clangd = {},
		cmake = {},
		ltex = {},
		lua_ls = {},
		marksman = {},
		pyright = {},
		ruff = {},
		svlangserver = {},
		verible = {},
		vhdl_ls = {},
	},
	linters = {},
	formatter = {
		-- asmfmt = {},
		beautysh = {},
		latexindent = {},
		["markdown-toc"] = {},
		prettier = {},
		rustfmt = {},
		stylua = {},
		yamlfmt = {},
	},
	others = {
		rust_analyzer = {},
	},
}
