[[cable_channel]]
name = "videos"
source_command = 'fd -t f -H -e mp4 -e mov -e avi -e mkv -e flv -e wmv -e mpg -e mpeg -e m4v -e 3gp -e webm -e vob -e ogv .'
preview_command = ':files:'

[[cable_channel]]
name = "zathura_files"
source_command = 'fd -t f -H -e pdf -e djvu -e ps -e cbz -e cbr -e epub -e mobi .'
preview_command = ':files:'

[[cable_channel]]
name = "pictures"
source_command = 'fd -t f -H -e jpg -e jpeg -e png -e gif -e bmp -e tiff -e tif -e svg -e webp -e heic .'
preview_command = ':files:'
