[[cable_channel]]
name = "files-hidden"
source_command = "fd -t f -H -E .git -E .cache"
preview_command = "bat -n --color=always {}"


[[cable_channel]]
name = "dirs"
source_command = "fd -t d -H -E .git -E .cache"
preview_command = "eza --long --git --all --color=always --icons=always {}"
