[[cable_channel]]
name = "zsh-history"
source_command = "sed '1!G;h;$!d' ${HISTFILE:-${HOME}/.zsh_history} | cut -d\";\" -f 2-"

[[cable_channel]]
name = "bash-history"
source_command = "sed '1!G;h;$!d' ${HISTFILE:-${HOME}/.bash_history}"
